# Min core temp (°C) - ARM / x86 compliant
UserParameter=basicCPUTemp.min,sensors | awk -F'[+°]' '/temp[0-9]+:/ {if(min==""||$2<min)min=$2} END{print min}'
 
# Max core temp (°C) - ARM / x86 compliant
UserParameter=basicCPUTemp.max,sensors | awk -F'[+°]' '/temp[0-9]+:/ {if(max==""||$2>max)max=$2} END{print max}'

# Avg core temp (°C) - ARM / x86 compliant
UserParameter=basicCPUTemp.avg,sensors | awk -F'[+°]' '/temp[0-9]+:/ {sum+=$2; n++} END{if(n>0)print sum/n}'
